name: movie_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  authentication:
    path: packages/authentication
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  dartz: ^0.10.1
  dio: ^5.1.2
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  formz: ^0.6.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  omdb:
    path: packages/omdb
  path: ^1.8.2
  path_provider: ^2.0.15
  validators:
    path: packages/validators

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/google_fonts/
    - assets/svg/
